permalink: /404.html
title: Jack's Dev Portfolio
description: This is a Website containing all of my completed and ongoing projects.
remote_theme: pages-themes/modernist@v0.2.0
plugins: jekyll-remote-theme